apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306        # Service port inside the cluster
      targetPort: 3306  # Must match container's listening port
      protocol: TCP
  type: ClusterIP